language: python
sudo: required
dist: trusty
notifications:
  email: false
before_install:
  - sudo echo "deb http://apt.openvstorage.org unstable main" | sudo tee -a /etc/apt/sources.list
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes openvstorage volumedriver-server
before_script:
  - sudo rm -rf /opt/OpenvStorage
  - sudo chmod 777 /opt
  - sudo chmod -R 777 /var/log/ovs
  - sudo chmod 777 /run
  - mv ../framework /opt/OpenvStorage
  - sudo cp /opt/OpenvStorage/scripts/system/ovs /usr/bin/
  - sudo chmod 777 /usr/bin/ovs
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages
script:
  - ovs unittest
